=== octocoach/octocoach/packages/azav/schema.json
{"type":"object","properties":{"name":{"type":"string"},"certificationNumber":{"type":"string"},"address":{"type":"object","properties":{"street":{"type":"string"},"number":{"type":"number","exclusiveMinimum":0},"city":{"type":"string"},"postalCode":{"type":"integer","exclusiveMinimum":0}},"required":["street","number","city","postalCode"],"additionalProperties":false},"email":{"type":"string","format":"email"},"website":{"type":"string","format":"uri"},"phone":{"type":"string","pattern":"^(?:\\+49|0)(?:\\s*\\d{2,5}\\s*){1,2}\\d{4,}$","errorMessage":{"pattern":"Invalid telephone number"}},"employees":{"type":"object","properties":{"fullTime":{"type":"integer","minimum":0},"partTime":{"type":"number","minimum":0},"external":{"type":"integer","minimum":0}},"required":["fullTime","partTime","external"],"additionalProperties":false},"subjectAreas":{"type":"object","properties":{"fb1":{"type":"boolean"},"fb2":{"type":"boolean"},"fb3":{"type":"boolean"},"fb4":{"type":"boolean"},"fb5":{"type":"boolean"},"fb6":{"type":"boolean"}},"required":["fb1","fb2","fb3","fb4","fb5","fb6"],"additionalProperties":false},"head":{"type":"object","properties":{"firstName":{"type":"string"},"lastName":{"type":"string"},"email":{"type":"string","format":"email"},"phone":{"$ref":"#/properties/phone"},"birthYear":{"type":"integer","minimum":1900},"birthPlace":{"type":"string"},"positionStart":{"$ref":"#/properties/head/properties/birthYear"},"qualifications":{"type":"array","items":{"type":"object","properties":{"institution":{"type":"string"},"qualification":{"type":"string"},"completionYear":{"$ref":"#/properties/head/properties/birthYear"}},"required":["institution","qualification","completionYear"],"additionalProperties":false}},"experience":{"type":"array","items":{"type":"object","properties":{"description":{"type":"string","maxLength":140},"type":{"type":"string"},"institution":{"type":"string"},"startDate":{"type":"string","format":"date-time"},"endDate":{"type":"string","format":"date-time"}},"required":["description","type","institution","startDate","endDate"],"additionalProperties":false}}},"required":["firstName","lastName","email","phone","birthYear","birthPlace","positionStart","qualifications","experience"],"additionalProperties":false},"deputyHead":{"$ref":"#/properties/head"},"measures":{"type":"object","properties":{"fb1":{"$ref":"#/properties/subjectAreas/properties/fb1"},"fb4":{"$ref":"#/properties/subjectAreas/properties/fb4"}},"required":["fb1","fb4"],"additionalProperties":false},"$schema":{"type":"string"}},"required":["name","address","email","website","phone","employees","subjectAreas","head","measures"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}

=== octocoach/octocoach/packages/azav/data/institution.json
{
  "name": "OctoCoach",
  "email": "info@octo.coach",
  "address": {
    "street": "Mulvanystraße",
    "number": 2,
    "city": "Düsseldorf",
    "postalCode": 40239
  },
  "website": "https://octo.coach",
  "phone": "+49 176 5537 5225",
  "subjectAreas": {
    "fb1": true,
    "fb2": false,
    "fb3": false,
    "fb4": false,
    "fb5": false,
    "fb6": false
  },
  "employees": {
    "fullTime": 1,
    "partTime": 0,
    "external": 0
  },
  "head": {
    "firstName": "Adriaan",
    "lastName": "van der Bergh",
    "email": "adriaan@octo.coach",
    "phone": "+49 176 5537 5225",
    "birthYear": 1981,
    "birthPlace": "Kempton Park, Südafrika",
    "positionStart": 2023,
    "qualifications": [
      {
        "institution": "University of South Africa",
        "qualification": "Bachelor of Education (B.Ed)",
        "completionYear": 2008
      },
      {
        "institution": "Endicott College",
        "qualification": "Master of Education (M.Ed)",
        "completionYear": 2014
      }
    ],
    "experience": [
      {
        "institution": "SuperCode GmbH & Co. KG",
        "type": "Vollzeitbeschäftigung",
        "description": "Trainer für Webentwicklung",
        "startDate": "2020-01-01T00:00:00+01:00",
        "endDate": "2020-12-31T00:00:00+01:00"
      },
      {
        "institution": "International School of Düsseldorf e.V.",
        "type": "Vollzeitbeschäftigung",
        "description": "Technologie-Integrations-Coach für Lehrkräfte",
        "startDate": "2011-01-01T00:00:00+01:00",
        "endDate": "2019-12-31T00:00:00+01:00"
      }
    ]
  },
  "measures": {
    "fb1": true,
    "fb4": false
  },
  "$schema": "../schema.json"
}
